default: &default
  adapter: postgresql
  encoding: utf8
  pool: 20
  timeout: 5000
  username: <%= ENV.fetch("DB_USER", nil) %>
  password: <%= ENV.fetch("DB_PASSWORD", nil) %>

development:
  <<: *default
  database: deploylist_development

test:
  <<: *default
  database: deploylist_test
